runtime: python39

# Service name change required
service: default

instance_class: F1

entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app
# handlers:
#   # Serve all static files with url ending with a file extension
#   - url: /(.*\..+)$
#     static_files: \1
#     upload: (.*\..+)$

#   # Catch all handler to index.html
#   - url: /.*
#     static_files: frontend/dist/index.html
#     upload: frontend/dist/index.html
